include:
  - project: technology/utils/cicd/gitlab-ci-pipeline-templates
    ref: TECH-249/tagging
    file:
      - workflow.gitlab-ci.yml
      - docker.buildx.gitlab-ci.yml

semantic:release:test:
  image: node:16.14-alpine
  stage: release
  variables:
    GL_TOKEN: ${GL_TOKEN}
  before_script:
    - apk update && apk add git ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab --save-dev
  script:
    - semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
