include:
  - project: technology/utils/cicd/gitlab-ci-pipeline-templates
    ref: TECH-249/tagging
    file:
      - workflow.gitlab-ci.yml
      - docker.buildx.gitlab-ci.yml
      - release.gitlab-ci.yml
